Bug Fix: Client Login Validation
omerk2511/TakiServer pull request #8
Opened 2020-10-16 08:40 UTC by yaimgod

2020-10-16 08:49 UTC, Nisitay requested changes

2020-10-16 08:49 UTC, Nisitay commented on source/handlers/server.py
> +                print '[-] unknown exception: ', e
The space is not necessary, the comma adds a space automatically

2020-10-16 08:49 UTC, Nisitay commented on source/games/game.py
> +    def does_player_exiset(self,sock):
The function name has a typo. I think you meant "does_player_exist" but I think "does_sock_exist" would be more fitting

2020-10-16 08:49 UTC, Nisitay commented on source/controllers/game.py
> +    if does_player_exiset(sock):
Shouldn't the game object check if the socket already exists? (in the "add_player" func in game.py)

2020-10-17 18:58 UTC, omerk2511 requested changes
Good job. I would like you to save a list of clients instead of socks in the Game object, and also change the name of the argument in games/games.py and also in the relevant decorators (authenticated and validator).

2020-10-18 15:41 UTC, omerk2511 requested changes
Excellent work

2020-10-18 15:41 UTC, omerk2511 commented on source/controllers/game.py
> +def leave_game_controller( client):
The arguments of this function should be: `user, args, client`

2020-10-18 15:41 UTC, omerk2511 commented on source/controllers/game.py
> +    if not client.in_game:
Please create a `@not_in_game` decorator.

2020-10-18 20:23 UTC, omerk2511 approved these changes

2020-10-18 20:24 UTC, Nisitay approved these changes

2020-10-18 20:24 UTC, merged